"""
Django settings for cityhall project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import mimetypes
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!ggs-f&a09lno$ikl)okp^s-ylw2gbomq3n^xh-ft@fh#zv9k6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["cityhall-nginx", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restless',
    'api',
    'viewer',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'cityhall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cityhall.wsgi.application'
ASGI_APPLICATION = 'cityhall.asgi.application'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


mimetypes.add_type("application/javascript", "*.js", True)
mimetypes.add_type("text/css", "*.css", True)

################################################################
# These are City Hall specific options
################################################################

CITY_HALL_OPTIONS = {
    'cache': {
        'path_capacity': 50,
        'env_capacity': 10,
    },

    'redis_cache': {
        # how long things should live in the cache in seconds
        # things like indexes of paths or environment roots
        'lifetime_seconds': '3600',

        # where this redis is located
        'host': 'cityhall-redis',
    },

    # Type of database connection.
    # This is honored by api.db.Connection.get_new_db()
    # Current possible options are: 'django' or 'memory'
    'db_type': 'django',

    # What type of cache to use
    'cache_type': 'redis',

    'version': 1,
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

try:
    # if we've been docker-compose'd all this will work:

    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': os.environ['POSTGRES_DBNAME'],
            'USER': os.environ['POSTGRES_USER'],
            'PASSWORD': os.environ['POSTGRES_PASS'],
            'HOST': 'cityhall-db',
            'PORT': '5432'
        }
    }
except:
    # if we reached here, that means os.environ[] above threw an error,
    # so, let's default back to sqlite and local cache

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
    
    CITY_HALL_OPTIONS['cache_type'] = 'local'
